'use client'

import { useState } from 'react'
import { ChevronLeft, ChevronRight, Quote } from 'lucide-react'
import { motion } from 'framer-motion'
import { Reveal } from './reveal'

const faqs = [['Is this a free download?', 'Yes. The digital edition is complimentary and delivered directly to your inbox.'], ['What format is the e-book available in?', 'You will receive a beautifully formatted PDF that is easy to read on any device.'], ['Can I share the e-book with my friends?', 'Absolutely. If someone you love could use these words, please pass the link along.'], ['Who is this book for?', 'It is for anyone learning to make room for their own voice, healing, and becoming.'], ['How long is the read?', 'A quiet, thoughtful read designed to meet you where you are and stay with you afterward.']] as const
const notes = [['Amelia Grace', 'A gentle reminder that choosing yourself is not selfish — it is essential.', '/rosara-author.png'], ['Ethan Grace', 'I finished the book feeling lighter, understood, and ready to begin again.', '/love-yourself-book.png'], ['Nadia Rahman', 'The kind of story you keep beside you for the days you need it most.', '/rosara-author.png'], ['Maya Chen', 'Every chapter felt like a quiet conversation with the part of me I had forgotten.', '/love-yourself-book.png'], ['Lina Brooks', 'Tender, honest, and beautifully grounding. I will return to these pages often.', '/rosara-author.png']] as const

export function Testimonials() {
  const [active, setActive] = useState(0);
  const move = (step: number) => setActive((active + step + notes.length) % notes.length);
  return <section id="reviews" className="bg-[#fff0e9] px-6 py-24 lg:px-10"><div className="mx-auto max-w-[1180px]"><Reveal className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#ff5c37]">✦ Reader notes</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Stories that touched the heart.</h2></Reveal><div className="relative mx-auto mt-10 h-[560px] max-w-[1280px] overflow-hidden">{notes.map(([name, quote, image], index) => { const offset = (index - active + notes.length) % notes.length; const position = offset > 2 ? offset - notes.length : offset; const center = position === 0; return <motion.article key={name} onClick={() => setActive(index)} animate={{ x: `calc(-50% + ${position * 205}px)`, y: center ? 10 : position % 2 ? 45 : -5, rotate: center ? 0 : position % 2 ? 3 : -3, scale: center ? 1 : .88, opacity: Math.abs(position) > 2 ? 0 : center ? 1 : .82 }} transition={{ type: 'spring', stiffness: 180, damping: 22 }} className={`absolute left-1/2 top-1 h-[330px] w-[270px] cursor-pointer rounded-[26px] border p-7 shadow-sm sm:h-[365px] sm:w-[365px] ${center ? 'z-10 border-[#ff5c37] bg-[#882c30] text-white shadow-[8px_10px_0_#ff5c37]' : 'z-0 border-[#17212c]/10 bg-white text-[#17212c]'}`}><img src={image} alt="" className="mb-5 size-14 rounded-xl object-cover object-top" /><Quote size={22} className={center ? 'text-[#ff8a45]' : 'text-[#ff5c37]'} /><p className="mt-5 text-lg leading-7">“{quote}”</p><p className={`absolute bottom-7 left-7 text-sm font-semibold ${center ? 'text-white/75' : 'text-[#17212c]/55'}`}>— {name}</p></motion.article> })}<div className="absolute bottom-2 left-1/2 z-20 flex -translate-x-1/2 gap-3"><button onClick={() => move(-1)} aria-label="Previous testimonial" className="grid size-12 place-items-center rounded-full border border-[#17212c]/15 bg-white hover:bg-[#ff5c37] hover:text-white"><ChevronLeft /></button><button onClick={() => move(1)} aria-label="Next testimonial" className="grid size-12 place-items-center rounded-full border border-[#17212c]/15 bg-white hover:bg-[#ff5c37] hover:text-white"><ChevronRight /></button></div></div></div></section>
}

export function FAQ() {
  const [open, setOpen] = useState(0);
  return <section id="faq" className="mx-auto max-w-[850px] px-6 py-24"><Reveal className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#ff5c37]">✦ FAQ</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em]">Frequently asked questions</h2></Reveal><Reveal delay={.1} className="mt-10"><div className="rounded-2xl bg-[#ff5c37] p-6 text-sm text-white"><strong>How do I download the book?</strong><p className="mt-2 text-white/80">Fill out the form above and the e-book will arrive in your inbox.</p></div><div className="mt-4 divide-y divide-[#17212c]/10 border-y border-[#17212c]/10">{faqs.map(([question, answer], index) => <div key={question}><button className="flex w-full items-center justify-between py-5 text-left text-sm font-medium" onClick={() => setOpen(open === index ? -1 : index)}>{question}<span className="text-xl font-light">{open === index ? '−' : '+'}</span></button>{open === index && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="pb-5 pr-8 text-sm leading-6 text-[#17212c]/55">{answer}</motion.p>}</div>)}</div></Reveal></section>
}
